In [1]:
import numpy as np

In [2]:
#create a rank 1 array

a = np.array([1, 2, 3])   

print(type(a))  

<class 'numpy.ndarray'>


In [3]:
#print shape of matrix
a.shape

(3,)

In [4]:
a[0]

1

In [5]:
a[0]
a[1]
a[2]

3

In [6]:
#accessing matrix elements
a[0],a[1],a[2]

(1, 2, 3)

In [7]:
#fill matrix with zeros
z = np.zeros((2,2))

In [8]:
z

array([[0., 0.],
       [0., 0.]])

In [9]:
#fill matrix with one
z = np.ones((2,2))

In [10]:
z

array([[1., 1.],
       [1., 1.]])

In [11]:
#fill matrix with the given no.
a=np.full((3,3),10)

In [12]:
a

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [13]:
#create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#create random matrix 
np.random.random((5,6))

array([[0.63102391, 0.09920708, 0.40246262, 0.59911711, 0.9111979 ,
        0.48075002],
       [0.42590034, 0.83356887, 0.05674446, 0.39936118, 0.00994542,
        0.6903353 ],
       [0.01585512, 0.20621702, 0.03583045, 0.20781981, 0.76860891,
        0.62221998],
       [0.36164705, 0.39117067, 0.8407177 , 0.73180135, 0.84135484,
        0.32855847],
       [0.66380018, 0.79195232, 0.93355495, 0.63376177, 0.98260474,
        0.64599852]])

In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [16]:
#slicing an numpy array
b = a[:2, 1:3]

In [17]:
b

array([[2, 3],
       [6, 7]])

In [18]:
a[0,1]

2

In [19]:
b[0,0]=55

In [20]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
a[0,1]

55

In [21]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

In [22]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [23]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[55  6 10] (3,)
[[55]
 [ 6]
 [10]] (3, 1)


In [28]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(3),b[:3]])

[1 6 7]


In [34]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[61  2  3]
 [ 4  5 66]
 [67  8  9]
 [10 71 12]]


In [35]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   

# Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

In [36]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [37]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[a > 2])  

[3 4 5 6]


In [41]:
#basic maths operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)
np.sqrt(x)

array([[ 6,  8],
       [10, 12]])

In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [43]:
# Inner product of vectors; both produce 219
print(np.dot(v, w))

219


In [44]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(np.dot(x, v))

[29 67]


In [45]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(np.dot(x, y))

[[19 22]
 [43 50]]
